name: Codegen

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codegen:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Codegen - Vector
        run: cmd /c "cd codegen && python vector_codegen.py"

      - name: Copy outputs to src
        run: copy "codegen\output\*" "src\gdmath"

#      - name: Validate
#        run: pip install .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: codegen_results
          path: codegen/output/
          retention-days: 5
